# Imagem base com Python
FROM python:3.11-slim

# Criar diretório de trabalho
WORKDIR /app

# Copiar arquivos
COPY requirements.txt .
COPY app.py .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta
EXPOSE 5000

# Comando de inicialização
CMD ["python", "app.py"]
